export const pincodeData = {
  "741402": ["2no.Natunfulia", "Belemath", "Buincha", "Fulia Colony", "Gazipur", "Tarapur"],
  "741137": ["Akanda Danga", "Akandaberia", "Arbetai", "Ashachia", "Bara Atagi", "Bilkumari", "Dingel", "Dhubinagadi", "Ghoraikhetra", "Haranagar", "Kamari", "Madandanga", "Majhergram", "Mahurapur", "Palit Behgia", "Sapjola", "Senpur"],
  "741245": ["Alaipur", "Ananda Nagar", "Chandamari", "Ghoragacha", "Kalipur", "Madanpur", "Saguna"],
  "741317": ["Aluipara", "Joania", "Joania Bhaluka"],
  "741318": ["Amghata"],
  "741101": ["Aminbazar", "Bowbazar", "Golapati", "Kathuriapara", "Krishnanagar", "Krishnanagar Court", "Krishnanagar R.s.", "Krishnanagar Road r.s.", "Nadia School board", "Nagendranagar", "Natunbazar", "Roypara", "Ukilpara"],
  "741165": ["Amiya Narayanpur", "Barbakpur", "Fajil Nagar", "Goas", "Gopalpur", "Kishorepur", "Mrigi", "Nandanpur", "Nazirpur", "Rahamatpur", "Tarakganj", "Topla"],
  "741125": ["Anandanagar", "Belpukur", "Mayakole", "Rajapur", "Shondanga", "Tatla"],
  "741253": ["Anishmali", "Eruli"],
  "741255": ["Anulia", "Haradham", "Nandighat"],
  "741122": ["Arabpur", "Bagchi Jamsherpur", "Bansberia", "Deuli", "Gopalpur Ghat", "Hogal Beria", "Joyrampur", "Kachharia Para", "Lalpur", "Nadiasundalpur", "Natna Patabuka", "Poradanga", "Sanyalchar"],
  "741501": ["Arangahta", "Barbaria", "Churni Raghunathpur", "Panchberia", "Purbanowpara"],
  "741121": ["Arbandi", "Badkulla", "Bapukinagar", "Bhaduri", "Boalia", "Chandra", "Khamarshumulia", "Mamjaon"],
  "741126": ["Arpara", "Bandbelgaon", "Bethuadahari", "Bholadanga", "Bikrampur", "Chinchuria", "Dhananjoypur", "Gotepara", "Harinarayanpur", "Jugpur Colony", "Khidirpur Bethuadahari", "Malumgachha", "Nakashipara", "Radhanagar Colony", "Sonadanga", "Taibichara", "Uttar Bahirgachhi"],
  "741404": ["Ashanandapara Street", "Bablagobindapur", "Bagachra", "Barabazar", "Barajiakur", "Gayeshpur Hazratala", "Ghoralia", "Haripurnadia", "Khandakhola", "Krishnakalitala", "Kutirpara", "Ramnagarchar", "Santipur", "Santipur College", "Santipur Rs", "Shyamchandpara", "Sutragarh"],
  "741161": ["Assannagar", "Kulgachi", "Rampur"],
  "741316": ["Bablari", "Bahirchara", "Fakirdanga", "Idrakpur", "Mahisura", "Srirampur"],
  "741123": ["Bagberia", "Banjaljhee", "Charuitipi", "Dompukuria", "Hridaypur", "Kalyandaha", "Lakshmipur", "Mahakhola", "Padmamala", "Pipragachhi", "Ranabanda", "Talukhuda"],
  "741502": ["Bagula", "Benali", "Bhairabchandrapur", "Bhayna", "Chupria", "Garapota-nadia", "Haldipara", "Haritala", "Kumari Ramnagar", "Mayurhat", "Muraghachacolony", "Nabarupdaha", "Patikabari", "Santinagar", "Taraknagar", "Ulashi"],
  "741183": ["Bahadurpur"],
  "741154": ["Bahirgachhi", "Digha", "Gachha", "Ghateswar", "Kamarhati", "Muragachha", "Rukunpur", "Saligram", "Suksagar"],
  "741152": ["Bajitpur", "Charmuktarpur", "Dhighalkandi", "Dhoradaha", "Karimpur", "Khanpur", "Natiadanga", "Pashim Dogachi", "Pipulberia", "Senpara", "Thanarpara"],
  "741155": ["Bakshipur", "Baur", "Bhawanipur", "Binod Nagar", "Gopinathpur", "Palashipara", "Shyamnagar"],
  "741156": ["Bali", "Bareya", "Barui Para", "Chhotonalda", "Dhawapara", "Molandi", "Palsunda", "Panchdara Abhaynagar", "Plassey", "Sahebnagar", "Shyamnagar (murshidabad)", "Tungi"],
  "741223": ["Balia", "Darappur", "Gouripur", "Hinghnara", "Purbabishnupur", "Rajarmath", "Silinda"],
  "741187": ["Baliadanga"],
  "741153": ["Baliadanga Faridpur", "Charchua Danga", "Matiari"],
  "741313": ["Bamunpukur", "Ganja Danga", "Nidaya", "Sreemayapur"],
  "741124": ["Baniakhari", "Bara Andulia", "Hatisala", "Matchpota", "Petuabhanga", "Teghari"],
  "741503": ["Banpur", "Bijoypur", "Gede", "Raghu Nandan pur"],
  "741150": ["Bara Kul beria", "Basarkhola", "Juranpur", "Kaliganj", "Manikdihi"],
  "741196": ["Barachand Ghar"],
  "741221": ["Barajaguli"],
  "741504": ["Baranberia", "Duttapulia"],
  "741168": ["Barnia"],
  "741507": ["Bathangachi", "Fatepur Majdia", "Gazna", "Majdia", "Mathurapur", "Putikhali"],
  "741250": ["Bedibhavan", "Kataganj"],
  "741256": ["Begopara", "Dayabari", "Ranaghat Baidyapur"],
  "741103": ["Berij", "Bhanderkhola", "Char Sambhu nagar", "Dhopatta", "Goaldaha", "Ghurni", "Jahangirpur", "Maliapota", "Nadia Bishnupur", "Patharghata", "Putimari", "Radhanagar", "Sonda", "Sutia", "Taranipur"],
  "741163": ["Betai", "Chhitkadaspara", "Karuigachi", "Lalbazar"],
  "741505": ["Betna", "Daharbuincha", "Hanskhali"],
  "741224": ["Bhagirathisilpaashram"],
  "741514": ["Bhajanghat"],
  "741181": ["Bharatpur", "Paglachandi", "Radhakantapur"],
  "741102": ["Bhatjangla", "Jalalkhali", "Jhitkipota", "Joypur", "Kalamari", "Saktinagar"],
  "741167": ["Bhimpur", "Sakdaha"],
  "741157": ["Bhurulia", "Plassey Sugar mill"],
  "741235": ["Bidhanpark", "Buddhapark", "Gandhi Memorial hospital", "Ghoshpara", "Kalyani", "Kalyani Hospital", "Kalyani Rs", "Kalyani Simanta", "Kalyani University"],
  "741319": ["Bidyanagar"],
  "741138": ["Billwagram", "Dharmada", "Kandoa", "Tentulberia"],
  "741127": ["Birnagar", "Byaspur"],
  "741225": ["Birohiedso"],
  "741201": ["Biswaspara", "Chotobazar", "Chunuripara", "Hijuli", "Matikumra", "Mahaprabhupara", "Panpara", "Ramnagaredso", "Ranaghat", "Ranaghat Bazar", "Ranaghat College", "Ranaghat Court", "Ranaghat Rs", "Ranaghat Rupashreepally", "Siddheswaritala"],
  "741222": ["Chakdah", "Deuli", "Dighra", "Ghetugachi", "Jasra", "Kadambagachi", "Kamalpuredso", "Khosbasmahalla", "Lalpur", "Poradanga", "Sanyalchar"],
  "741510": ["Chandandaha"],
  "741509": ["Chandannagar", "Chowgacha", "Shibnibas"],
  "741162": ["Chandanpur", "Dadupur Nadia", "Kasiadanga", "Udaychandrapur"],
  "741169": ["Chanderghat"],
  "741248": ["Chanduria", "Narapatipara", "Rautari", "Simurali"],
  "741202": ["Chapra", "Dhantala", "Halalpur-krishnapur", "Nasra"],
  "741151": ["Chapri", "Chitrasali", "Dhakshinpara", "Itaberia"],
  "741301": ["Char Brahmanagar", "Ushidpur"],
  "741170": ["Charatala"],
  "741251": ["Charsarhati", "Majerchar", "Netajisubhas Sanatorium"],
  "741160": ["Chhatina", "Iswarchandrapur", "Jitpur", "Khaspur", "Krishna chandrapur", "Natna", "Nischantapur", "Notiapota", "Raghunathpur", "Tehatta"],
  "741171": ["Chhoto Andulia"],
  "741232": ["Cooper's Camp"],
  "741192": ["Dakshin Bahirgachhi"],
  "741140": ["Dalimoula", "Dhubulia T b hospital", "Nowpara", "Panditpur", "Rupdaha"],
  "741511": ["Daluabari"],
  "741158": ["Darermath", "Raghunthpur-ramnagar", "Shikarpur"],
  "741164": ["Dayer Bazar", "Ichhapur", "Madhabpur", "Mahatpur", "Tilakpur"],
  "741302": ["Dearapara", "Buroshibtala", "Kolerdanga", "Moti Roy bandh", "Nabadwip", "Nabadwip Bazar", "Nabadwip Dham rs", "Poramatala Road", "Pratapnagar", "Rudrapara", "Tegharipara"],
  "741238": ["Debagram", "Gangnapur", "Gangsara Majhergram", "Ghola", "Gopinagar", "Humaniapota", "Naserkuli", "Uzirpukuria"],
  "741257": ["Dighalgram", "Haripukuria", "Kasthadanga", "Mahadevpur", "Nagarukhra", "Nimtala Bazar"],
  "741401": ["Dignagar"],
  "741185": ["Dogachhi"],
  "741506": ["Durgapur", "Krishnaganj", "Swarnakhali", "Tangra"],
  "741249": ["Fatepur", "Mollabelia", "Narayanpur", "Panpur", "Simhat", "Subarnapur"],
  "741405": ["Fulia Boyra"],
  "741315": ["Gadigachha", "Mahesganj", "Swarupganj"],
  "741234": ["Gayeshpur"],
  "741512": ["Gobindapur"],
  "741188": ["Gobrapota"],
  "741403": ["Habibpur"],
  "741173": ["Hanspukuria"],
  "741246": ["Haringhat River research insti", "Mohanpur"],
  "741189": ["Haripur Chhitka"],
  "741513": ["Hatbahirgachi"],
  "741203": ["Jm Nokari"],
  "741508": ["Joyghata", "Khalboalia", "Maheshpur", "Nadiasumalia", "Digambarpur"],
  "741254": ["Kalinarayanpur", "Kamgachi"],
  "741166": ["Kalinga", "Seemanagar"],
  "741184": ["Kalirhat"],
  "741172": ["Kechuadanga"],
  "741252": ["Krishivisyavidyalaya"],
  "741258": ["Noapara"],
  "741247": ["Pritinagar"],
  "741515": ["Shibnarayanpur"],
  "741191": ["Shibpur"],
  "741159": ["Taherpur"],
  "741516": ["Taldaha"]
};
